import Head from "next/head";
import { AiFillGithub, AiFillFacebook, AiFillInstagram } from "react-icons/ai";
import Image from "next/image";
import deo from "../public/profile2.png";
import icon from "../public/figmaa.svg";
import website from "../public/website.svg";
import figma from "../public/project.png";
import web_1 from "../public/project1.png";
import web_2 from "../public/project2.png";
import tailwind from "../public/tailwind.png";
import react from "../public/react.png";
import nextjs from "../public/next.png";
import React from "react";
import js from "../public/javascripts.png";
import Navbar from "./Navbar";
import php from "../public/php.png";
import node from "../public/node.png";
import { motion } from "framer-motion";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Pacman Portofolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/profile.png' />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40  '>
        <section className=' min-h-screen'>
          <React.StrictMode>
            <Navbar />
          </React.StrictMode>
          <motion.div
            className='text-center pt-44'
            initial={{ x: "-100vw" }}
            animate={{ x: 0 }}
            transition={{ type: "spring", duration: 1, bounce: 0.3 }}>
            <h2 className='text-4xl py-2 text-cyan-500 font-medium md:text-6xl'>
              Putu Adelio
            </h2>
            <h3 className='text-xl py-2  md:text-3xl'>
              Devoloper and Designer.
            </h3>
            <p className='text-md py-5 mx-auto leading-8 text-gray-800 max-w-lg md:text-xl'>
              A 15-year-old student who wants to become a developer and designer
              said. Learning with limited devices will not make your spirit go
              down
            </p>
          </motion.div>
          <motion.div
            className='text-4xl flex justify-center gap-16 py-3 text-gray-600 md:text-5xl'
            initial={{ x: "-100vw" }}
            animate={{ x: 0 }}
            transition={{ type: "spring", duration: 1, bounce: 0.3 }}>
            <a
              className='hover:text-cyan-500 hover:-translate-y-1 hover:scale-110 
              duration-300'
              href='https://github.com/PyAde'>
              <AiFillGithub />
            </a>
            <a
              className='hover:text-cyan-500 hover:-translate-y-1 hover:scale-110 
              duration-300 '
              href='https://www.facebook.com/profile.php?id=100072114708290'>
              <AiFillFacebook />
            </a>
            <a
              className='hover:text-cyan-500 hover:-translate-y-1 hover:scale-110 
              duration-300'
              href='https://www.instagram.com/putudodo_1/'>
              <AiFillInstagram />
            </a>
          </motion.div>
          <motion.div
            className='relative mx-auto max-w-lg  w-80 h-80 mt-10 overflow-hidden'
            initial={{ x: "100vw" }}
            animate={{ x: 0 }}
            transition={{ type: "spring", duration: 1, bounce: 0.3 }}>
            <Image src={deo} alt='Foto profil' />
          </motion.div>
        </section>
        <section id='skill'>
          <motion.div
            className='pt-56 pb-10'
            initial={{ opacity: 0, scale: 0 }}
            whileInView={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6 }}>
            <h3 className='text-3xl py-1 text-center font-medium text-cyan-500'>
              My Skill
            </h3>
            <p className='text-md text-center leading-8 text-gray-800'>
              Skills that I have acquired during the course
            </p>
          </motion.div>
          <div className='w-full px-4 flex flex-wrap justify-center xl:justify-between xl:w-10/12 xl:mx-auto'>
            <motion.div
              initial={{ opacity: 0, scale: 0 }}
              whileInView={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.6 }}
              className='text-center shadow-xl p-10 md:w-1/2 rounded-xl my-10 duration-300'>
              <Image src={icon} alt='icon' className='mx-auto w-12 h-12' />
              <h3 className='text-lg font-medium pt-8 pb-2'>Design</h3>
              <p>I am able to create UI and UX designs</p>
              <a href='https://www.figma.com/'>
                <h4 className='text-cyan-500 p-5'>Figma</h4>
              </a>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, scale: 0 }}
              whileInView={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.6 }}
              className='text-center shadow-xl md:w-1/2 p-10 rounded-xl  max-w-full my-10 duration-300 md:mx-auto'>
              <Image src={website} alt='icon' className='mx-auto w-12  h-12 ' />
              <h3 className='text-lg font-medium pt-8 pb-2'>Web Developer</h3>
              <p>
                That,s great! Being able to create a website using programming
                languages and frameworks is a valuable skill
              </p>
              <a href='https://code.visualstudio.com/'>
                <h4 className='text-cyan-500 p-5'>Visual Studio Code</h4>
              </a>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, scale: 0 }}
              whileInView={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.6 }}
              className='text-center shadow-xl md:w-1/2 p-10 rounded-xl my-10 duration-300 w-full '>
              <div class='flex flex-col items-start mr-5'>
                <h2 class='mb-4 text-2xl font-medium text-cyan-500'>
                  Front End
                </h2>
                <div class='flex flex-col items-start mb-4'>
                  <div class='flex items-center'>
                    <Image src={tailwind} alt='icon' class='w-12 h-12' />
                    <h3 class='text-lg font-medium mr-4'>Tailwind</h3>
                  </div>
                </div>
                <div class='flex flex-col items-start mb-4'>
                  <div class='flex items-center'>
                    <Image src={react} alt='icon' class='w-12 h-12' />
                    <h3 class='text-lg font-medium mr-4'>React Js</h3>
                  </div>
                </div>
                <div class='flex flex-col items-start mb-4'>
                  <div class='flex items-center'>
                    <Image src={nextjs} alt='icon' class='w-12 h-12' />
                    <h3 class='text-lg font-medium mr-4'>Next Js</h3>
                  </div>
                </div>
                <div class='flex flex-col items-start'>
                  <div class='flex items-center'>
                    <Image src={js} alt='icon' class='w-12 h-12' />
                    <h3 class='text-lg font-medium mr-4'>JavaScripts</h3>
                  </div>
                </div>
              </div>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, scale: 0 }}
              whileInView={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.6 }}
              className='text-center shadow-xl md:w-1/2 p-10 rounded-xl my-10 duration-300 w-full '>
              <div class='flex flex-col items-start mr-5'>
                <h2 class='mb-4 text-2xl font-medium text-cyan-500'>
                  Back End
                </h2>
                <div class='flex flex-col items-start mb-4'>
                  <div class='flex items-center'>
                    <Image src={php} alt='icon' class='w-12 h-12' />
                    <h3 class='text-lg font-medium mr-4'>PhP</h3>
                  </div>
                </div>
                <div class='flex flex-col items-start mb-4'>
                  <div class='flex items-center'>
                    <Image src={node} alt='icon' class='w-12 h-12' />
                    <h3 class='text-lg font-medium mr-4'>Node Js</h3>
                  </div>
                </div>
                <div class='flex flex-col items-start'>
                  <div class='flex items-center'>
                    <Image src={nextjs} alt='icon' class='w-12 h-12' />
                    <h3 class='text-lg pr-10 font-medium mr-4 md:pr-0'>
                      Next Js
                    </h3>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </section>
        <section id='project'>
          <motion.div
            initial={{ opacity: 0, scale: 0 }}
            whileInView={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6 }}
            className='text-center pt-60 pb-32'>
            <h3 className='text-3xl py-1 text-center text-cyan-500'>
              My Projects
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 mx-auto max-w-lg'>
              I created this project based on a course and personal learning. I
              made this project during my free time and when I didnt have any
              school assignments.
            </p>
          </motion.div>
          <div>
            <div>
              <div className='w-full px-4 flex flex-wrap justify-center xl:w-10/12 xl:mx-auto'>
                <div
                  className='mb-12 px-4 md:w-1/2 xl:w-1/2  hover:-translate-y-1 hover:scale-110 
              duration-300'>
                  <motion.div
                    initial={{ opacity: 0, scale: 0 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.6 }}
                    className='rounded-md shadow-md overflow-hidden'>
                    <Image src={web_1} alt='web1' className='w-full' />
                    <h3 className='font-medium text-xl text-cyan-500 text-center'>
                      Link Tree{" "}
                    </h3>
                  </motion.div>
                </div>
                <div
                  className='mb-12 px-4 md:w-1/2 xl:w-1/2  hover:-translate-y-1 hover:scale-110 
              duration-300'>
                  <motion.div
                    initial={{ opacity: 0, scale: 0 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.6 }}
                    className='rounded-md shadow-md overflow-hidden'>
                    <Image src={web_2} alt='web2' className='w-full' />
                    <h3 className='font-medium text-xl text-cyan-500 text-center'>
                      Web Personal CSS
                    </h3>
                  </motion.div>
                </div>
                <div
                  className='mb-12 px-4 md:w-1/2 xl:w-1/2  hover:-translate-y-1 hover:scale-110 
              duration-300'>
                  <motion.div
                    initial={{ opacity: 0, scale: 0 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.6 }}
                    className='rounded-md shadow-md overflow-hidden'>
                    <Image src={figma} alt='web2' className='w-full' />
                    <h3 className='font-medium text-xl text-cyan-500 text-center'>
                      Desain Figma
                    </h3>
                  </motion.div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <footer class='pt-52 pb-12'>
          <div class='container'>
            <div class='w-full pt-10 border-t border-cyan-700'>
              <p class='font text-xs text-cyan-500 text-center md:text-xl'>
                Dibuat oleh{" "}
                <a
                  href='https://www.instagram.com/pyadeoop_01/'
                  target='_blank'
                  class='font-bold text-xs text-cyan-500 md:text-xl'>
                  PyAdeOOP
                </a>
              </p>
            </div>
          </div>
        </footer>
      </main>
    </div>
  );
}
